version: "3.7"

services:
  # サービス名は自由に設定
  django:
    # appディレクトリの中から`Dockerfile`を探す
    build: ./app
    # データを永続化させる場合の設定。`host:container`でパスを記載
    volumes:
      - ./app/:/usr/src/app/
      - mydata:/root/
    # 開放するポートを指定。`host:container`でポートを記載
    ports:
      - 8000:8000
    tty: true
    environment:
      - DEBUG=1
      - SECRET_KEY=testkey
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_DB=django_db
      - DATABASE_USER=django_db_user
      - DATABASE_PASSWORD=password1234
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE=postgres
    depends_on:
      - postgres
    env_file:
      - .env.app

  postgres:
    # 公式からイメージをpull
    image: postgres:11.4-alpine
    # データベースの永続化
    # ホストのディレクトリにマウントしない様に、先頭に`./`をつけない
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # su権限を持つ、指定されたユーザーと同じ名前のデータベースを作成
    # valueはdjangoサービスで指定したものと同じ様に記載する
    environment:
      - POSTGRES_USER=django_db_user
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=django_db
    env_file:
      - .env.db

# トップレベルに書く「名前付きvolumes」は複数サービスから参照できる
volumes:
  mydata:
  postgres_data:
