# Generated by Django 2.2.12 on 2020-06-24 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル 40文字以内')),
                ('search_tag', models.CharField(max_length=100, verbose_name='検索タグ (100文字以内空白区切りで入力してください)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Article',
            },
        ),
        migrations.CreateModel(
            name='UploadImageByFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='mediafiles')),
            ],
            options={
                'verbose_name_plural': 'UploadImageByFile',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='ユーザー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wooys.Article', verbose_name='記事')),
            ],
        ),
        migrations.CreateModel(
            name='Browsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='閲覧日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wooys.Article', verbose_name='記事')),
            ],
        ),
    ]
