# Generated by Django 2.2.12 on 2020-06-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageByFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='mediafiles/')),
            ],
            options={
                'verbose_name_plural': 'UploadImageByFile',
            },
        ),
    ]
