# Generated by Django 2.2.12 on 2020-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='browse_num',
            field=models.IntegerField(default=0, verbose_name='閲覧数'),
        ),
        migrations.AddField(
            model_name='article',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='いいね数'),
        ),
    ]
