# Generated by Django 2.2.12 on 2020-06-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagebyfile',
            name='img',
            field=models.ImageField(null=True, upload_to='mediafiles'),
        ),
    ]
