# Generated by Django 2.2.12 on 2020-06-10 11:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wooys', '0002_auto_20200609_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagebyfile',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='mediafiles'),
        ),
    ]
