# Generated by Django 2.2.12 on 2020-06-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooys', '0005_auto_20200626_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=40, verbose_name='ユーザー名'),
        ),
    ]
