# Generated by Django 2.2.12 on 2020-06-18 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wooys', '0006_auto_20200618_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good',
            new_name='GoodLike',
        ),
    ]
