# Generated by Django 2.2.13 on 2020-07-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooys', '0007_auto_20200627_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagebyfile',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
