apiVersion: v1
kind: Service
metadata:
  name: skaffold-wooys-lb
  labels:
    app: skaffold-wooys-lb
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: skaffold-wooys-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-wooys-app
  labels:
    app: skaffold-wooys-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skaffold-wooys-app
  template:
    metadata:
      labels:
        app: skaffold-wooys-app
    spec:
      containers:
        - name: nginx
          image: hdys/wooys-nginx
          envFrom:
            - secretRef:
                name: kubernetes-secret
          env:
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 80
          # volumeMounts:
          #   - name: staticfiles-volume
          #     mountPath: /usr/src/app/staticfiles
        - name: django
          image: hdys/wooys-django
          envFrom:
            - secretRef:
                name: kubernetes-secret
          env:
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 8000
      #     volumeMounts:
      #       - name: staticfiles-volume
      #         mountPath: /usr/share/nginx/html/staticfilrs
      # volumes:
      #   - name: staticfiles-volume
      #     emptyDir: {}
